publication_top_name: "Help with Health Costs (HwHC)"
publication_sub_name: "England April 2019 to March 2024"
publication_date: "20 June 2024"
responsible_statistician: "Steven Buckley"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
