publication_top_name: "Help with Health Costs (HwHC)"
publication_sub_name: "2019/20 to 2023/24"
publication_date: "20 June 2024"
responsible_statistician: "Steven Buckley"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
publication_table_title: "Help with Health Costs (HwHC) - 2019/20 to 2023/24"

# data table criteria
rebuild_base_data: FALSE
extract_date_lis: "20240409"
extract_date_hes: "20240409"
extract_date_hrt: "20240503"
extract_px_min_ym: 202304
extract_px_max_ym: 202403
extract_px_age_dt: 20230930   # date to use to calculate patient age

# time period criteria
min_trend_ym_lis: "201804"
min_trend_active_ym_lis: "201904" # need to check impact of deleted records to choose period
max_trend_ym_lis: "202403"
min_focus_ym_lis: "202304"
max_focus_ym_lis: "202403"

min_trend_ym_mat: "201804"
min_trend_active_ym_mat: "201904" # need to check impact of deleted records to choose period
max_trend_ym_mat: "202403"
min_focus_ym_mat: "202304"
max_focus_ym_mat: "202403"

min_trend_ym_med: "201804"
min_trend_active_ym_med: "201904" # need to check impact of deleted records to choose period
max_trend_ym_med: "202403"
min_focus_ym_med: "202304"
max_focus_ym_med: "202403"

min_trend_ym_ppc: "201804"
max_trend_ym_ppc: "202403"
min_focus_ym_ppc: "202304"
max_focus_ym_ppc: "202403"

min_trend_ym_tax: "201804"
max_trend_ym_tax: "202403"
min_focus_ym_tax: "202304"
max_focus_ym_tax: "202403"

min_focus_ym_hrt: "202304"
max_focus_ym_hrt: "202403"

# base population criteria
ons_pop_year: "2022"
lis_min_pop_age: 16
lis_max_pop_age: 90
mat_min_pop_age: 15
mat_max_pop_age: 45
med_min_pop_age: 16
med_max_pop_age: 59
ppc_min_pop_age: 16
ppc_max_pop_age: 59
tax_min_pop_age: 16
tax_max_pop_age: 90
hrt_min_pop_age: 16
hrt_max_pop_age: 59
ons_pop_rate_denominator: 10000

# ONS live birth criteria
ons_births_year: "2021"
ons_birth_geo_table: "ONS_BIRTHS_GEOGRAPHY_AGEBAND"
ons_birth_imd_table: "ONS_BIRTHS_IMD"

# ICB classification
icb_classification: 2023
